import = ["~/.config/alacritty/themes/themes/everforest_light_medium.toml"]
[window]
decorations= "None"
startup_mode= "Maximized"
dynamic_padding=true
option_as_alt="Both"
[font]
normal= {family="Hack Nerd Font Mono", style="Regular"}
size= 12.0
[terminal]
osc52="CopyPaste"
[mouse]
hide_when_typing=true
